### PR TITLE
Feature/strategy replace on root object

### PR DESCRIPTION
**Pull request by thabemmz**

### CODE REVIEW

**Comment by thabemmz** [comment]
@bsander updated

**Comment by thabemmz** [comment]
@bsander updated, can be merged

**Comment by thabemmz** [comment]
@bsander I checked this pending PR and the following is fixed by applying this PR:
- `_strategies` on both configs and properties in those configs were not taken into account by environments.

E.g., imagine the following default config:
```
config: {
  foo: 'bar',
  lorem: 'ipsum'
}
```

and the following prod config:
```
config: {
  _strategy: 'replace',
  quick: 'brown'
}
```

In the current situation, this leads to the following config for `prod`:
```
config: {
  foo: 'bar',
  lorem: 'ipsum',
  quick: 'brown'
```

In the new situation, this leads to the following config for `prod`:
```
config: {
  quick: 'brown'
}
```

The same holds for config properties like arrays when applying a `noconcat` strategy on them in the `prod` environment.

**Comment by bsander** [comment]
Nice :)

**Pull request merged**
