### PR TITLE
TC-1020: Keep strategy directive around long enough for proper merge

### PR DESCRIPTION
**Pull request by roelandvanbatenburg**
### Ticket
Link to ticket: https://enrise.atlassian.net/browse/TC-1020

### What has been done
- Only delete the `_strategy` directive after the merge has completed, not before it starts. This requires all strategy implementations to perform the delete action when they are done.
- Updated eslint rules

### How to test
- Failing unit test now succeeds
- Try with case discovered in ticket

### CODE REVIEW

**Comment by roelandvanbatenburg** [comment]
@bsander I can't review this (probably because I created the PR). Looks good to me, however I'm curious why this hasn't been an issue before.

**Comment by roelandvanbatenburg** [comment]
@bsander turns out my original test did not quite cover the use case, added another test.

**Comment by roelandvanbatenburg** [comment]
Btw, if you move the `_instances: true` on level1 to the icin, it behaves properly

**Comment by thabemmz** [comment]
Tomorrows I will write some documentation for this.

**Comment by roelandvanbatenburg** [comment]
@bsander can't add my review as I started this PR...

**Review by bsander — APPROVED** [review]
LGTM, is this mergable or still waiting for the docs update? @thabemmz

**Comment by roelandvanbatenburg** [comment]
Discussed it with @thabemmz documentation is not for now 😞

**Comment by thabemmz** [comment]
Yeah, I cannot write a README of this that soon. That will have to wait until later.

**Pull request merged**
